#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/).
# All system path must be relative, except initrd dirs.
# License: GPL last version. Лицензия: GPL последней версии.
# Author: Alexey Loginov.
# Автор: Алексей Логинов.
#
export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

. etc/sysconfig/MagicOS

VER=`cat /VERSION|awk '{print $2}'`

FIND_VER=`cat etc/once_boot_scripts|grep $VER`
if [ "$FIND_VER" = "" ]
then
 rm -f etc/once_boot_scripts > /dev/null
fi

ONCE=`cat etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

#Fix bug https://bugs.mageia.org/show_bug.cgi?id=14638
ln -s /usr/sbin/lpc usr/bin/lpc

echo $(basename $0)-$VER >> etc/once_boot_scripts
