#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. /liblinuxlive
. etc/sysconfig/MagOS

VER=`cat /VERSION|awk '{print $2}'`

FIND_VER=`cat etc/once_boot_scripts|grep $VER`
if [ "$FIND_VER" = "" ]
then
 rm -f etc/once_boot_scripts > /dev/null
fi

ONCE=`cat etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

#Fix: Unable to find a valid menu file "/usr/share/lxde/openbox/menu.xml"
#http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=644756
mkdir -p etc/skel/.config/openbox
chmod 777 etc/skel/.config/openbox
ln -s /usr/share/lxde/openbox/menu.xml etc/skel/.config/openbox/menu.xml

#Fix bug https://bitbucket.org/carlmig/radio-tray/issue/146/dont-work-without-home-local-share
mkdir -p etc/skel/.local
chmod 777 etc/skel/.local
mkdir -p etc/skel/.local/share
chmod 777 etc/skel/.local/share

#Fix bug http://code.google.com/p/mandriva-lxde/issues/detail?id=4
mkdir -p etc/skel/.config
chmod 777 etc/skel/.config
mkdir -p etc/skel/.config/autostart
chmod 777 etc/skel/.config/autostart

echo $(basename $0)-$VER >> etc/once_boot_scripts
