#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/).
# All system path must be relative, except initrd dirs.
# License: GPL last version. Лицензия: GPL последней версии.
# Author: Alexey Loginov.
# Автор: Алексей Логинов.
#
export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

VER=`cat /VERSION|awk '{print $2}'`
ONCE=`cat etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

. etc/sysconfig/MagicOS

rm -f usr/share/applications/squeak.desktop

#sankore is buggy for LXDE with mcompmgr
A=`cat usr/share/applications/sankore.desktop|grep NotShowIn|grep LXDE`
if [ "$A" = "" ]
then
  echo "NotShowIn=LXDE;" >> usr/share/applications/sankore.desktop
fi

#ardesia is buggy for LXDE with mcompmgr
A=`cat usr/share/applications/ardesia.desktop|grep NotShowIn|grep LXDE`
if [ "$A" = "" ]
then
  echo "NotShowIn=LXDE;" >> usr/share/applications/ardesia.desktop
fi

sed -i "/OnlyShowIn=/d" usr/share/applications/xfce4-terminal.desktop

usermod -G italc user

#update-desktop-database
#update-mime-database usr/share/mime

echo $(basename $0)-$VER >> etc/once_boot_scripts
