#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/).
# All system path must be relative, except initrd dirs.
# License: GPL last version. Лицензия: GPL последней версии.
# Authors: Alexandr Betkher, Anton Goroshkin, Mikhail Zaripov, Alexey Loginov.
# Авторы: Александр Бетхер, Антон Горошкин, Михаил Зарипов, Алексей Логинов.
#
export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

. etc/sysconfig/MagicOS

[ $(cmdline_parameter depmod) ] && DEPMOD="yes"
[ "$DEPMOD" = "yes" ] && chroot . sbin/depmod -a

