#!/bin/bash
# Initial script for MagicOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

MODULESPRELOAD="nfsd"
BLACKLISTMODULES="$(cmdline_value blacklist | tr ',;' ' ')"
. etc/sysconfig/MagicOS

for a in $(echo $MODULESPRELOAD | tr , " ") ;do
    echo " $BLACKLISTMODULES " | grep -q " $a " || chroot . modprobe $a
done
