#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/).
# All system path must be relative, except initrd dirs.
# License: GPL last version. Лицензия: GPL последней версии.
# Authors: Alexandr Betkher, Anton Goroshkin, Mikhail Zaripov, Alexey Loginov.
# Авторы: Александр Бетхер, Антон Горошкин, Михаил Зарипов, Алексей Логинов.
#
export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

. etc/sysconfig/MagicOS

#Profile updating
grep -q -f /VERSION etc/magicos-release 2>/dev/null || rm -fr /memory/changes/var/lib/rpm  /memory/changes/var/lib/urpmi 2>/dev/null
cp -f /VERSION etc/magicos-release

#Fix bug "no /dev/kmsg for logging" when system is booting
mknod -m 660 dev/kmsg c 1 11

VER=`cat /VERSION|awk '{print $2}'`
ONCE=`cat etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

#Boot
ln -sf $(ls boot/vmlinuz-* | tail -1 | sed 's|boot/||') boot/vmlinuz
ln -sf $(ls boot/System.map-* | tail -1 | sed 's|boot/||') boot/System.map
ln -sf $(ls boot/config-* | tail -1 | sed 's|boot/||') boot/config
ln -sf /mnt/livemedia/MagicOS/initrd.gz boot/initrd.gz

#Optimization menu and correction desktop files
rm -f usr/share/applications/chbg.desktop
rm -f usr/share/applications/localedrake-user.desktop
rm -f usr/share/applications/xscreensaver-properties.desktop
rm -f usr/share/applications/obconf.desktop
rm -f usr/share/applications/xlockmore.desktop
rm -f usr/share/applications/lxappearance.desktop
rm -f usr/share/applications/libfm-pref-apps.desktop
rm -f usr/share/applications/mdvinput.desktop
rm -f usr/share/applications/lxinput.desktop
rm -f usr/share/applications/lxsession-edit.desktop
rm -f usr/share/applications/lxsession-default-apps.desktop
rm -f usr/share/applications/pcmanfm-desktop-pref.desktop
A=`cat usr/share/applications/kde4/systemsettings.desktop | grep OnlyShowIn=KDE;`
#https://bugs.mageia.org/show_bug.cgi?id=13949
sed -i 's|Exec=.*|Exec=systemsettings -caption "%c" %i|g' usr/share/applications/kde4/kdesystemsettings.desktop

sed -i "/OnlyShowIn=/d" usr/share/applications/qt-recordmydesktop.desktop
sed -i "/OnlyShowIn=/d" usr/share/applications/caja.desktop
sed -i "/OnlyShowIn=/d" usr/share/applications/mate-dictionary.desktop
sed -i "/OnlyShowIn=/d" usr/share/applications/mate-screenshot.desktop
sed -i "/OnlyShowIn=/d" usr/share/applications/mate-search-tool.desktop
sed -i "/NotShowIn=/d" usr/share/applications/scim-setup.desktop
sed -i "/OnlyShowIn=/d" usr/share/applications/kde4/krandrtray.desktop
sed -i "/OnlyShowIn=/d" usr/share/applications/kde4/kfind.desktop

#Fix MIME for engrampa
sed -i -e 's|application/x-ms-dos-executable;||g' usr/share/applications/engrampa.desktop
sed -i -e 's|application/x-rpm;||g' usr/share/applications/engrampa.desktop

#Correction mcc
sed -i -e "s|'Snapshots',|#'Snapshots',|g" usr/libexec/drakconf
sed -i -e 's|"Mageia Update",|#"Mageia Update",|g' usr/libexec/drakconf
sed -i -e 's|"Boot Config",|#"Boot Config",|g' usr/libexec/drakconf
sed -i -e 's|"3D",|#"3D",|g' usr/libexec/drakconf

#Correction lxde-ctrl-center
if [ -f "usr/bin/lxde-ctrl-center" ]
then
  sed -i "/drakrpm-update/d" usr/share/lxde-ctrl-center/items/x0003x
  sed -i "/drakrpm-update/d" usr/share/lxde-ctrl-center/items/advanced
  sed -i "/drakedm/d" usr/share/lxde-ctrl-center/items/x0005x
  sed -i "/drakedm/d" usr/share/lxde-ctrl-center/items/advanced
fi

#Add lxde-ctrl-center to LXPanel
if [ -f "usr/bin/lxde-ctrl-center" ]
then
  sed -i -e 's|id=lxterminal.desktop|id=lxde-ctrl-center.desktop|g' etc/xdg/lxpanel/LXDE/panels/panel
fi

#Add background for MATE and LXDE
rm -f usr/share/mga/backgrounds/Mageia-Default-*
rm -f usr/share/mga/backgrounds/default.jpg
ln -s Mageia1600x1200.jpg usr/share/mga/backgrounds/Mageia-Default-1024x600.jpg
ln -s Mageia1600x1200.png usr/share/mga/backgrounds/Mageia-Default-1024x600.png
ln -s Mageia1600x1200.jpg usr/share/mga/backgrounds/Mageia-Default-1280x1024.jpg
ln -s Mageia1600x1200.png usr/share/mga/backgrounds/Mageia-Default-1280x1024.png
ln -s Mageia1600x1200.jpg usr/share/mga/backgrounds/Mageia-Default-1920x1080.jpg
ln -s Mageia1600x1200.png usr/share/mga/backgrounds/Mageia-Default-1920x1080.png
ln -s Mageia1600x1200.jpg usr/share/mga/backgrounds/Mageia-Default-1920x1200.jpg
ln -s Mageia1600x1200.png usr/share/mga/backgrounds/Mageia-Default-1920x1200.png
ln -s Mageia1600x1200.jpg usr/share/mga/backgrounds/Mageia-Default-1920x1440.jpg
ln -s Mageia1600x1200.png usr/share/mga/backgrounds/Mageia-Default-1920x1440.png
ln -s Mageia1600x1200.jpg usr/share/mga/backgrounds/Mageia-Default-800x480.jpg
ln -s Mageia1600x1200.png usr/share/mga/backgrounds/Mageia-Default-800x480.png
ln -s Mageia1600x1200.jpg usr/share/mga/backgrounds/default.jpg

#Add background for KDE
if [ ! -f "usr/share/mga/backgrounds/default.png" ]
then
  ln -s Mageia1600x1200.png usr/share/mga/backgrounds/default.png
fi
rm -f usr/share/wallpapers/Mageia/contents/images/800x480.png
rm -f usr/share/wallpapers/Mageia/contents/images/1024x600.png
rm -f usr/share/wallpapers/Mageia/contents/images/1280x1024.png
rm -f usr/share/wallpapers/Mageia/contents/images/1920x1080.png
rm -f usr/share/wallpapers/Mageia/contents/images/1920x1200.png
rm -f usr/share/wallpapers/Mageia/contents/images/1920x1440.png
ln -s /usr/share/mga/backgrounds/default.png usr/share/wallpapers/Mageia/contents/images/800x480.png
ln -s /usr/share/mga/backgrounds/default.png usr/share/wallpapers/Mageia/contents/images/1024x600.png
ln -s /usr/share/mga/backgrounds/default.png usr/share/wallpapers/Mageia/contents/images/1280x1024.png
ln -s /usr/share/mga/backgrounds/default.png usr/share/wallpapers/Mageia/contents/images/1920x1080.png
ln -s /usr/share/mga/backgrounds/default.png usr/share/wallpapers/Mageia/contents/images/1920x1200.png
ln -s /usr/share/mga/backgrounds/default.png usr/share/wallpapers/Mageia/contents/images/1920x1440.png

#Fix https://bugs.mageia.org/show_bug.cgi?id=10224
A=`cat etc/rc.d/rc.local|grep loadkeys|grep ru`
if [ "$A" = "" ]
then
  echo "loadkeys -u ru" >> etc/rc.d/rc.local
fi

#For mate-screenshot
if [ ! -f "usr/share/pixmaps/applets-screenshooter.png" ]
then
  if [ -f "usr/share/icons/mate/48x48/apps/applets-screenshooter.png" ]
  then
    ln -s /usr/share/icons/mate/48x48/apps/applets-screenshooter.png usr/share/pixmaps/applets-screenshooter.png
  fi
fi

#For sweeper
if [ ! -f "usr/share/pixmaps/trash-empty.png" ]
then
  if [ -f "usr/share/icons/oxygen/48x48/actions/trash-empty.png" ]
  then
    ln -s /usr/share/icons/oxygen/48x48/actions/trash-empty.png usr/share/pixmaps/trash-empty.png
  fi
fi

#For krandr
if [ ! -f "usr/share/pixmaps/preferences-desktop-display-randr.png" ]
then
  if [ -f "usr/share/icons/oxygen/48x48/apps/preferences-desktop-display.png" ]
  then
    ln -s /usr/share/icons/oxygen/48x48/apps/preferences-desktop-display.png usr/share/pixmaps/preferences-desktop-display-randr.png
  fi
fi

#For PrintScreen in LXDE
if [ ! -f "usr/bin/gnome-screenshot" ]
then
  if [ -f "usr/bin/mate-screenshot" ]
  then
    ln -s /usr/bin/mate-screenshot usr/bin/gnome-screenshot
  fi
fi

A=`cat usr/share/applications/draknetcenter.desktop|grep Comment`
if [ "$A" = "" ]
then
   echo "Comment=Mageia Network Center" >> usr/share/applications/draknetcenter.desktop
fi

A=`cat usr/share/applications/kde4/konsole.desktop|grep Comment`
if [ "$A" = "" ]
then
  sed -i "s|Name=Konsole|Name=Konsole\nComment=Konsole\nComment[ru]=Консоль|g" usr/share/applications/kde4/konsole.desktop
fi

A=`cat usr/share/applications/xfburn.desktop|grep GenericName`
if [ "$A" = "" ]
then
  sed -i "s|Name=Xfburn|Name=Xfburn\nGenericName=CD and DVD burning application\nGenericName[ru]=Приложение для записи CD и DVD|g" usr/share/applications/xfburn.desktop
fi

A=`cat usr/share/applications/hardinfo.desktop|grep Comment`
if [ "$A" = "" ]
then
   echo "Comment=System Information" >> usr/share/applications/hardinfo.desktop
fi

A=`cat usr/share/applications/hardinfo.desktop|grep GenericName`
if [ "$A" = "" ]
then
   echo "GenericName=Hardware Information" >> usr/share/applications/hardinfo.desktop
fi

sed -i "s|^Name\[ru\]=.*|Name[ru]=Gpicview - просмотр изображений|g" usr/share/applications/gpicview.desktop

sed -i "s|^Name\[ru\]=.*|Name[ru]=KSysGuard - системный монитор|g" usr/share/applications/kde4/ksysguard.desktop

#update-desktop-database
#update-mime-database usr/share/mime

echo $(basename $0)-$VER >> etc/once_boot_scripts
