#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/).
# All system path must be relative, except initrd dirs.
# License: GPL last version. Лицензия: GPL последней версии.
# Authors: Alexandr Betkher, Anton Goroshkin, Mikhail Zaripov, Alexey Loginov.
# Авторы: Александр Бетхер, Антон Горошкин, Михаил Зарипов, Алексей Логинов.
#
export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

#Switch to graffical start and cancel for desktop=none later
rm -f etc/systemd/system/default.target
ln -s /lib/systemd/system/runlevel5.target etc/systemd/system/default.target
sed -i 's/id:.:initdefault:/id:5:initdefault:/' etc/inittab

for a in $(cmdline_value desktop | tr , " " ) ;do
   case $a in
       none)
         sed -i 's/id:.:initdefault:/id:3:initdefault:/' etc/inittab
         rm -f etc/systemd/system/default.target
         ln -s /lib/systemd/system/multi-user.target etc/systemd/system/default.target
       ;;
       kde)
         echo -e "DISPLAYMANAGER=KDM\nDESKTOP=KDE4" >etc/sysconfig/desktop
       ;;
       mate)
         echo -e "DISPLAYMANAGER=lxdm\nDESKTOP=MATE" >etc/sysconfig/desktop
       ;;
       lxde)
         echo -e "DISPLAYMANAGER=lxdm\nDESKTOP=LXDE" >etc/sysconfig/desktop
       ;;
       kdm)
         sed -i 's/DISPLAYMANAGER=.*/DISPLAYMANAGER=KDM/' etc/sysconfig/desktop
       ;;
       lxdm)
         sed -i 's/DISPLAYMANAGER=.*/DISPLAYMANAGER=lxdm/' etc/sysconfig/desktop
       ;;
   esac
done
