#!/bin/bash
# Initial script for MagicOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

rm -f etc/sysconfig/i18n
ln -s /etc/sysconfig/lang/default/i18n etc/sysconfig/i18n
rm -f etc/sysconfig/keyboard
ln -s /etc/sysconfig/lang/default/keyboard etc/sysconfig/keyboard

for a in $(cmdline_value lang | tr , " " ) ;do
  if [ -d "etc/sysconfig/lang/$a" ]
  then
    rm -f etc/sysconfig/i18n
    ln -s /etc/sysconfig/lang/$a/i18n etc/sysconfig/i18n
    rm -f etc/sysconfig/keyboard
    ln -s /etc/sysconfig/lang/$a/keyboard etc/sysconfig/keyboard
  fi
done
