#!/bin/bash

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

grep -q xdriver= /proc/cmdline && XORG_DRIVER=$(cat /proc/cmdline | awk -F xdriver= '{print $2}' | awk '{print $1}')
if [ ! "$XORG_DRIVER" = "" ]
then
  sed -i -e "/Section \"Device\"/!b;:x;n;s/Driver.*/Driver \"$XORG_DRIVER\"/;t;/Section/b;bx" /etc/X11/xorg.conf
fi
