#!/bin/bash

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

#xset dpms 0 0 0
#xset -dpms
#xset s off
#xset s 0 0

#VER=`cat /mnt/live/VERSION|awk '{print $2}'`
#ONCE=`cat /etc/once_boot_scripts|grep $(basename $0)-$VER`
#if [ ! "$ONCE" = "" ]
#then
#  exit 0
#fi

#A=`cat /etc/X11/xorg.conf|grep BlankTime`
#if [ "$A" = "" ]
#then
#  sed -i -e 's|Option "DPMS".*|Option "DPMS" "false"|g' /etc/X11/xorg.conf
#  sed -i -e "s|Identifier \"layout1\"|Identifier \"layout1\"\n    Option \"BlankTime\" \"0\"\n    Option \"StandbyTime\" \"0\"\n    Option \"SuspendTime\" \"0\"\n    Option \"OffTime\" \"0\"|" /etc/X11/xorg.conf
#fi

#echo $(basename $0)-$VER >> /etc/once_boot_scripts
