#!/bin/bash

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
debug_mode "$0" "$@"

#Fix: https://bugs.mageia.org/show_bug.cgi?id=8402
#modprobe snd_mixer_oss
