#!/bin/bash

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
debug_mode "$0" "$@"

VER=`cat /mnt/live/VERSION|awk '{print $2}'`
ONCE=`cat /etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

LANG0=`cat /etc/sysconfig/i18n|grep ru_RU`
if [ "$LANG0" = "" ]
then
  LANG=English
else
  LANG=Russian
fi

if [ "$LANG" = "Russian" ]
then
  rm -f /usr/share/peazip/res/lang/default.txt
  cp -f /usr/share/peazip/res/lang/ru.txt /usr/share/peazip/res/lang/default.txt
fi

echo $(basename $0)-$VER >> /etc/once_boot_scripts
