#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. /liblinuxlive
. etc/sysconfig/MagOS

VER=`cat /VERSION|awk '{print $2}'`
ONCE=`cat etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

mkdir -p proc
mount -o rbind /proc proc
if [ -x bin/systemd ]
then
  chroot . systemctl disable NetworkManager.service || chroot . chkconfig --del NetworkManager
else
  chroot . chkconfig --del NetworkManager
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable squid.service || chroot . chkconfig --del squid
else
  chroot . chkconfig --del squid
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable dansguardian.service || chroot . chkconfig --del dansguardian
else
  chroot . chkconfig --del dansguardian
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable freshclam.service || chroot . chkconfig --del freshclam
else
  chroot . chkconfig --del freshclam
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable nfs-server.service || chroot . chkconfig --del nfs-server
else
  chroot . chkconfig --del nfs-server
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable postfix.service || chroot . chkconfig --del postfix
else
  chroot . chkconfig --del postfix
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable msec.service || chroot . chkconfig --del msec
else
  chroot . chkconfig --del msec
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable lm_sensors.service || chroot . chkconfig --del lm_sensors
else
  chroot . chkconfig --del lm_sensors
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable proftpd.service || chroot . chkconfig --del proftpd
else
  chroot . chkconfig --del proftpd
fi
#if [ -x bin/systemd ]
#then
#  chroot . systemctl disable reboot.service || chroot . chkconfig --del reboot
#else
#  chroot . chkconfig --del reboot
#fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable systemd-readahead-collect.service || chroot . chkconfig --del systemd-readahead-collect
else
  chroot . chkconfig --del systemd-readahead-collect
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable systemd-readahead-replay.service || chroot . chkconfig --del systemd-readahead-replay
else
  chroot . chkconfig --del systemd-readahead-replay
fi
#if [ -x bin/systemd ]
#then
#  chroot . systemctl disable halt.service || chroot . chkconfig --del halt
#else
#  chroot . chkconfig --del halt
#fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable upsd.service || chroot . chkconfig --del upsd
else
  chroot . chkconfig --del upsd
fi
if [ -x bin/systemd ]
then
  chroot . systemctl disable upsmon.service || chroot . chkconfig --del upsmon
else
  chroot . chkconfig --del upsmon
fi
umount proc

echo $(basename $0)-$VER >> etc/once_boot_scripts
