#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

VER=`cat /VERSION|awk '{print $2}'`
ONCE=`cat etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

. /liblinuxlive
. etc/sysconfig/MagOS

#Optimization menu and correction desktop files
sed -i "/OnlyShowIn=/d" usr/share/applications/evolution-settings.desktop
sed -i -e 's|Icon=evolution|Icon=/usr/share/icons/hicolor/48x48/apps/evolution.png|g' usr/share/applications/evolution-settings.desktop
sed -i -e 's|Icon=evolution|Icon=/usr/share/icons/hicolor/48x48/apps/evolution.png|g' usr/share/applications/evolution.desktop
sed -i -e 's|Icon=thunderbird|Icon=/usr/share/icons/hicolor/48x48/apps/thunderbird.png|g' usr/share/applications/thunderbird.desktop
sed -i -e 's|Categories=Office|Categories=Office;X-MandrivaLinux-Office-Wordprocessors;|g' usr/share/applications/rodovid.desktop
#sed -i -e 's|Icon=cantor|Icon=/usr/share/icons/hicolor/48x48/apps/cantor.png|g' usr/share/applications/kde4/cantor.desktop
#Fix bug https://bugs.mageia.org/show_bug.cgi?id=10649
sed -i -e 's|  ||g' usr/share/applications/zhu3d.desktop

#Fix bug: https://bugs.mageia.org/show_bug.cgi?id=6055
rm -f usr/share/applications/scilab-cli.desktop
rm -f usr/share/applications/scilab-adv-cli.desktop

#Fix bug: https://bugs.mageia.org/show_bug.cgi?id=8421
sed -i -e 's|italc.png|italc.xpm|g' usr/share/applications/italc.desktop

sed -i -e 's|#Icon=gnome-terminal|Icon=gsharp.png|g' usr/share/applications/gsharp.desktop

#Fix bug: https://bugs.mageia.org/show_bug.cgi?id=8423
sed -i "/Icon=/d" usr/share/applications/edugraphe.desktop
echo "Icon=edugraphe" >> usr/share/applications/edugraphe.desktop

rm -f usr/share/applications/squeak.desktop
rm -f usr/share/applications/ilcontrast.desktop

#Link for QDevelop
if [ ! -f "usr/bin/ctags" ]
then
  ln -s /usr/bin/exuberant-ctags usr/bin/ctags
fi

#Fix for "Без имени" and for Basic for geany
sed -i -e 's|{untitled}|untitled|g' usr/share/geany/templates/files/program.pas
touch usr/share/geany/templates/files/program.bas

#Fix MIME
sed -i -e 's|<mime-info>|<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">|g' usr/share/mime/packages/freemind.xml
sed -i "/MimeType/d" usr/share/applications/mandriva-mucommander.desktop
#https://bugs.mageia.org/show_bug.cgi?id=10640
sed -i "/desktop:/d" usr/share/mime/packages/tupi.xml

#update-desktop-database
#update-mime-database usr/share/mime

echo $(basename $0)-$VER >> etc/once_boot_scripts
