#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# License: GPL last version. Лицензия: GPL последней версии.
# Authors: Alexandr Betkher, Anton Goroshkin, Mikhail Zaripov, Alexey Loginov.
# Авторы: Александр Бетхер, Антон Горошкин, Михаил Зарипов, Алексей Логинов.
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

gtk-update-icon-cache -fit /usr/share/icons/hicolor >/dev/null 2>&1
