#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# License: GPL last version. Лицензия: GPL последней версии.
# Authors: Alexey Loginov.
# Авторы: Алексей Логинов.
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

VER=`cat /mnt/live/VERSION|awk '{print $2}'`
ONCE=`cat /etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

ln -s /usr/lib/kde4/libexec/kdesu /usr/bin/

echo $(basename $0)-$VER >> /etc/once_boot_scripts
