#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# License: GPL last version. Лицензия: GPL последней версии.
# Author: Alexey Loginov.
# Автор: Алексей Логинов.
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

if [ -d "/home/user/Рабочий стол" ]
then
  cd "/home/user/Рабочий стол"
  chmod +x ./*.desktop
  chown user:user ./*.desktop
fi

if [ -d "/home/user/Desktop" ]
then
  cd "/home/user/Desktop"
  chmod +x ./*.desktop
  chown user:user ./*.desktop
fi

if [ ! -d "/run/media/user" ]
then
  mkdir -p /run/media/user
  chown -hR user:user /run/media
fi
