#!/bin/bash
#
# Initial script for MagicOS-Linux Live operating system.
# License: GPL last version. Лицензия: GPL последней версии.
# Author: Alexey Loginov.
# Автор: Алексей Логинов.
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive 2>/dev/null || . /mnt/live/liblinuxlive
#debug_mode "$0" "$@"

VER=`cat /mnt/live/VERSION|awk '{print $2}'`
ONCE=`cat /etc/once_boot_scripts|grep $(basename $0)-$VER`
if [ ! "$ONCE" = "" ]
then
  exit 0
fi

LANG0=`cat /etc/sysconfig/i18n|grep ru_RU`
if [ "$LANG0" = "" ]
then
  LANG=English
else
  LANG=Russian
fi

A=`cat /usr/share/applications/mageia-doc-mcc-ru.desktop|grep "NoDisplay="`
if [ ! "$A" = "" ]
then
  sed -i "/NoDisplay=/d" /usr/share/applications/mageia-doc-mcc-ru.desktop
fi

if [ ! "$LANG" = "Russian" ]
then
  echo "NoDisplay=true" >> /usr/share/applications/mageia-doc-mcc-ru.desktop
fi

echo $(basename $0)-$VER >> /etc/once_boot_scripts
